/**
 * The always-loaded instruction block every agent reads.
 *
 * It is generated from the project's own configuration and merged into
 * `AGENTS.md` / `CLAUDE.md` between markers, so a team keeps its own prose
 * around a block collab-swarm can keep current.
 */

import { ROLE_LABEL, SKILL_ROLES } from '../packs.js';
import type { EmitContext } from './types.js';

export const BLOCK_START = '<!-- collab-swarm:start -->';
export const BLOCK_END = '<!-- collab-swarm:end -->';

const table = (header: string[], rows: string[][]): string[] => [
  `| ${header.join(' | ')} |`,
  `| ${header.map(() => '---').join(' | ')} |`,
  ...rows.map((row) => `| ${row.join(' | ')} |`),
];

export function renderMemoryBlock(context: EmitContext, workflowRoot: string): string {
  const { config, packs } = context;
  const lines: string[] = [];

  lines.push(BLOCK_START);
  lines.push('<!-- Generated by collab-swarm. Edit collab-swarm.yml, then run `npx swarm sync`. -->');
  lines.push('');
  lines.push('## How work happens here');
  lines.push('');
  lines.push(
    'One feature is one plan. The contract is ' +
      `[\`${workflowRoot}/WORKFLOW.md\`](${workflowRoot}/WORKFLOW.md); ` +
      'invoke the skill rather than reimplementing its steps.',
  );
  lines.push('');
  lines.push('```text');
  lines.push('requirements → specification → tickets → implementation → review → complete');
  lines.push('```');
  lines.push('');
  lines.push(
    ...table(
      ['Say', 'What happens'],
      [
        [
          '`What\'s next?` / `How\'s it going?`',
          '`whats-next` reads the delivery board and proposes the best unclaimed rows; picking one claims it so nobody else is offered it',
        ],
        [
          '`Make a plan to implement <feature>`',
          '`deliver-change` runs `to-requirements`, `to-spec` and `to-tickets`, then presents the plan and stops',
        ],
        [
          '`Implement the plan`',
          'Tickets run in dependency order with `implement`, each verified with the project checks; then `code-review`',
        ],
        ['`Resume the <slug> plan`', 'Continues from the stage recorded in `plan.yml`'],
      ],
    ),
  );
  lines.push('');

  lines.push('## Golden rules');
  lines.push('');
  lines.push('Non-negotiable. A change that breaks one is not done, whatever else it achieves.');
  lines.push('');
  const rules: string[] = [
    `**Spec first.** Feature code exists only under a plan in \`${config.plans}/<slug>/\` with requirements, specification, and tickets. No plan, no code.`,
    Object.keys(config.sources).length > 0
      ? '**Grounded, not invented.** Behaviour comes from the sources listed below. A question the sources leave open is recorded and asked, never answered in code.'
      : '**Grounded, not invented.** Behaviour comes from the request and the code already here. A question neither answers is asked, never guessed.',
    "**Red before green.** Every behaviour change starts with a failing test at a public boundary named in the specification's test plan. Generated output, docs, and mechanical config may skip it; the ticket says why.",
    '**One owner per concern.** A second module owning the same state is a duplicate owner. Capture failures at the seam and return them as values; callers render loading, empty, failure, and content as distinct states.',
    '**Machine-owned files stay machine-owned.** Edit the annotated source and regenerate; never hand-edit generated output.',
    '**Secrets stay out.** Keys, tokens, and hashes never enter Git or a plan document.',
    config.checks.length > 0
      ? `**Checks pass before done.** \`${checkCommand(context)}\` is green before a ticket is marked done, before a commit, and before completion is reported. Report the real result; a skipped or failing check is stated, never implied green.`
      : '**Checks pass before done.** Run the project\'s own checks before a ticket is marked done. Report the real result; a skipped or failing check is stated, never implied green.',
  ];
  rules.forEach((rule, index) => lines.push(`${index + 1}. ${rule}`));
  lines.push('');

  const sources = Object.entries(config.sources);
  if (sources.length > 0) {
    lines.push('## Sources of truth');
    lines.push('');
    lines.push(
      ...table(
        ['Source', 'Where', 'Use it for'],
        sources.map(([key, source]) => [
          `${source.label}${source.required ? ' *(required)*' : ''}`,
          source.paths.map((path) => `\`${path}\``).join(', '),
          source.use ?? key,
        ]),
      ),
    );
    lines.push('');
  }

  if (config.backlog) {
    lines.push('## Delivery board');
    lines.push('');
    lines.push(
      `The feature register in [\`${config.backlog}\`](${config.backlog}) is the backlog and Git is the tracker: ` +
        `the branch \`${config.git.branchPrefix}<slug>\` on \`${config.git.remote}\` claims a row, and ` +
        `\`${config.plans}/<slug>/plan.yml\` complete on \`${config.git.defaultBranch}\` marks it done. ` +
        'Nothing outside the repository records state, so every developer and every agent sees the same board after one fetch.',
    );
    lines.push('');
  }

  if (config.checks.length > 0) {
    lines.push('## Commands');
    lines.push('');
    const commands: [string, string][] = [
      [checkCommand(context), 'the project checks; CI runs the same set'],
      [`${cli(context)} check --focus <path>`, 'ticket verification'],
      [`${cli(context)} validate`, 'the workflow contract and every plan'],
      [`${cli(context)} status`, 'the delivery board'],
    ];
    const width = Math.max(...commands.map(([command]) => command.length));
    lines.push('```bash');
    for (const [command, comment] of commands) {
      lines.push(`${command.padEnd(width)}  # ${comment}`);
    }
    lines.push('```');
    lines.push('');
  }

  const skills = [...packs.skills].sort((a, b) => a.name.localeCompare(b.name));
  if (skills.length > 0) {
    lines.push('## Skills');
    lines.push('');
    // Driven by the role list rather than a fixed set of groups, so a pack
    // that adds a router or a review skill still appears here.
    for (const role of SKILL_ROLES) {
      const named = skills.filter((skill) => skill.role === role);
      if (named.length === 0) continue;
      const label = ROLE_LABEL[role].replace(/^./, (first) => first.toUpperCase());
      lines.push(`- **${label}:** ${named.map((skill) => `\`${skill.name}\``).join(', ')}`);
    }
    lines.push('');
    lines.push(
      'Only skills in the *implements a ticket* group may appear in a ticket\'s `skills` list; the validator enforces it.',
    );
    lines.push('');
  }

  lines.push(BLOCK_END);
  return lines.join('\n');
}

export const cli = (_context: EmitContext) => 'npx swarm';

export const checkCommand = (context: EmitContext) => `${cli(context)} check`;

/** Inserts or replaces the managed block, leaving everything else untouched. */
export function mergeBlock(existing: string | null, block: string, title: string): string {
  if (existing === null || existing.trim() === '') {
    return `# ${title}\n\n${block}\n`;
  }
  const start = existing.indexOf(BLOCK_START);
  const end = existing.indexOf(BLOCK_END);
  if (start >= 0 && end > start) {
    return existing.slice(0, start) + block + existing.slice(end + BLOCK_END.length);
  }
  return `${existing.trimEnd()}\n\n${block}\n`;
}
